//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergeticProjectX.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergeticProjectX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВНИМАНИЕ: Если у этой категории есть товары, они могут быть удалены или остаться без категории!.
        /// </summary>
        internal static string AlertOfDeleteCategory {
            get {
                return ResourceManager.GetString("AlertOfDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить категорию.
        /// </summary>
        internal static string AskForDeleteCategory {
            get {
                return ResourceManager.GetString("AskForDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить этот товар?.
        /// </summary>
        internal static string AskForDeleteProduct {
            get {
                return ResourceManager.GetString("AskForDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите отменить редактирование?.
        /// </summary>
        internal static string AskOfCancelEdit {
            get {
                return ResourceManager.GetString("AskOfCancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string CategoryDisplayMember {
            get {
                return ResourceManager.GetString("CategoryDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category_Id.
        /// </summary>
        internal static string CategoryValueMember {
            get {
                return ResourceManager.GetString("CategoryValueMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы изменили пароль!.
        /// </summary>
        internal static string ChangePasswordEvent {
            get {
                return ResourceManager.GetString("ChangePasswordEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию для удаления.
        /// </summary>
        internal static string ChooseCategoryDelete {
            get {
                return ResourceManager.GetString("ChooseCategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию товара!.
        /// </summary>
        internal static string ChooseCategoryProduct {
            get {
                return ResourceManager.GetString("ChooseCategoryProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите клиента для редактирования..
        /// </summary>
        internal static string ChooseClientForEdit {
            get {
                return ResourceManager.GetString("ChooseClientForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию и/или новую единицу измерения для дальнейшего редактирования.
        /// </summary>
        internal static string ChooseEditCategoryAndNewUnit {
            get {
                return ResourceManager.GetString("ChooseEditCategoryAndNewUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите единицу измерения.
        /// </summary>
        internal static string ChooseUnit {
            get {
                return ResourceManager.GetString("ChooseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ContactInfo.
        /// </summary>
        internal static string ClientContactInfo {
            get {
                return ResourceManager.GetString("ClientContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИП.
        /// </summary>
        internal static string ClientContractorIndEntrepreneur {
            get {
                return ResourceManager.GetString("ClientContractorIndEntrepreneur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юр. лицо.
        /// </summary>
        internal static string ClientContractorLegalEntity {
            get {
                return ResourceManager.GetString("ClientContractorLegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Физ. лицо.
        /// </summary>
        internal static string ClientContractorPhysicalPerson {
            get {
                return ResourceManager.GetString("ClientContractorPhysicalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INN.
        /// </summary>
        internal static string ClientINN {
            get {
                return ResourceManager.GetString("ClientINN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClientCode.
        /// </summary>
        internal static string ClientRowCode {
            get {
                return ResourceManager.GetString("ClientRowCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contractor.
        /// </summary>
        internal static string ClientRowContractor {
            get {
                return ResourceManager.GetString("ClientRowContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string ClientRowName {
            get {
                return ResourceManager.GetString("ClientRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение отмены.
        /// </summary>
        internal static string ConfirmationCancel {
            get {
                return ResourceManager.GetString("ConfirmationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        internal static string ConfirmationDelete {
            get {
                return ResourceManager.GetString("ConfirmationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование категории.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пусто.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки категорий..
        /// </summary>
        internal static string ErrorCategoryUpload {
            get {
                return ResourceManager.GetString("ErrorCategoryUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить данные, так как они необходимы для отгрузки..
        /// </summary>
        internal static string ErrorClientDelete {
            get {
                return ResourceManager.GetString("ErrorClientDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить изменения..
        /// </summary>
        internal static string ErrorClientSaveChanges {
            get {
                return ResourceManager.GetString("ErrorClientSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении:.
        /// </summary>
        internal static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении категории.
        /// </summary>
        internal static string ErrorSaveCategory {
            get {
                return ResourceManager.GetString("ErrorSaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки единиц измерения..
        /// </summary>
        internal static string ErrorUnitUpload {
            get {
                return ResourceManager.GetString("ErrorUnitUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки данных:.
        /// </summary>
        internal static string ErrorUploadData {
            get {
                return ResourceManager.GetString("ErrorUploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки данных текущего пользователя..
        /// </summary>
        internal static string ErrorUserDataUpload {
            get {
                return ResourceManager.GetString("ErrorUserDataUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка валидации.
        /// </summary>
        internal static string ErrorValidation {
            get {
                return ResourceManager.GetString("ErrorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный логин уже существует..
        /// </summary>
        internal static string ExistsUsername {
            get {
                return ResourceManager.GetString("ExistsUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните все обязательные поля.
        /// </summary>
        internal static string FillRequiredFields {
            get {
                return ResourceManager.GetString("FillRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиентов загружено:.
        /// </summary>
        internal static string HowMuchClientsUploaded {
            get {
                return ResourceManager.GetString("HowMuchClientsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товара загружено:.
        /// </summary>
        internal static string HowMuchProductsUploaded {
            get {
                return ResourceManager.GetString("HowMuchProductsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователей загружено:.
        /// </summary>
        internal static string HowMuchUsersUploaded {
            get {
                return ResourceManager.GetString("HowMuchUsersUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль..
        /// </summary>
        internal static string IncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("IncorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введён некорректный старый пароль..
        /// </summary>
        internal static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат данных для ИНН..
        /// </summary>
        internal static string INNFormatError {
            get {
                return ResourceManager.GetString("INNFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификационный номер Юр. лица должен содержать 10 символов..
        /// </summary>
        internal static string INNRequirementsTenDigits {
            get {
                return ResourceManager.GetString("INNRequirementsTenDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИНН Физ. лица или ИП должен содержать 12 цифр..
        /// </summary>
        internal static string INNRequirementsTwelveDigits {
            get {
                return ResourceManager.GetString("INNRequirementsTwelveDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите новое название категории:.
        /// </summary>
        internal static string InputNewCategoryName {
            get {
                return ResourceManager.GetString("InputNewCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат GUID.
        /// </summary>
        internal static string InvalidGUIDFormat {
            get {
                return ResourceManager.GetString("InvalidGUIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, придумайте новый логин..
        /// </summary>
        internal static string InventNewLogin {
            get {
                return ResourceManager.GetString("InventNewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, придумайте новый пароль..
        /// </summary>
        internal static string InventNewPassword {
            get {
                return ResourceManager.GetString("InventNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы вошли в аккаунт.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все несохранённые изменения будут потеряны.
        /// </summary>
        internal static string LostUnsavedChanges {
            get {
                return ResourceManager.GetString("LostUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания уникального клиентского кода! Превышено допустимое число клиентов..
        /// </summary>
        internal static string MaxNumberOfClients {
            get {
                return ResourceManager.GetString("MaxNumberOfClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания артикула для товара! Превышено допустимое число товара..
        /// </summary>
        internal static string MaxNumberOfProducts {
            get {
                return ResourceManager.GetString("MaxNumberOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка назначения уникального клиентского кода! Превышено допустимое число пользователей..
        /// </summary>
        internal static string MaxNumberOfUsers {
            get {
                return ResourceManager.GetString("MaxNumberOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара на складе!.
        /// </summary>
        internal static string NotEnoughProductInStock {
            get {
                return ResourceManager.GetString("NotEnoughProductInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить пароль на уже существующий. Пожалуйста, придумайте новый пароль для замены!.
        /// </summary>
        internal static string OldAndNewPasswordsTheSame {
            get {
                return ResourceManager.GetString("OldAndNewPasswordsTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display.
        /// </summary>
        internal static string ProductDisplayMember {
            get {
                return ResourceManager.GetString("ProductDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар не найден!.
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Article.
        /// </summary>
        internal static string ProductValueMember {
            get {
                return ResourceManager.GetString("ProductValueMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display.
        /// </summary>
        internal static string RecipientDisplayMember {
            get {
                return ResourceManager.GetString("RecipientDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client_Id.
        /// </summary>
        internal static string RecipientValueMember {
            get {
                return ResourceManager.GetString("RecipientValueMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shipment_Id.
        /// </summary>
        internal static string ShipmentId {
            get {
                return ResourceManager.GetString("ShipmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка успешно оформлена!.
        /// </summary>
        internal static string ShipmentSuccessfullyProcessed {
            get {
                return ResourceManager.GetString("ShipmentSuccessfullyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория успешно добавлена!.
        /// </summary>
        internal static string SuccessAddCategory {
            get {
                return ResourceManager.GetString("SuccessAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория успешно удалена!.
        /// </summary>
        internal static string SuccessDeleteCategory {
            get {
                return ResourceManager.GetString("SuccessDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно удален!.
        /// </summary>
        internal static string SuccessDeleteProduct {
            get {
                return ResourceManager.GetString("SuccessDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория успешно обновлена!.
        /// </summary>
        internal static string SuccessUpdateCategory {
            get {
                return ResourceManager.GetString("SuccessUpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно обновлён!.
        /// </summary>
        internal static string SuccessUpdateProduct {
            get {
                return ResourceManager.GetString("SuccessUpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория с таким наименованием уже имеется в базе данных..
        /// </summary>
        internal static string ThereIsSuchCategory {
            get {
                return ResourceManager.GetString("ThereIsSuchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление.
        /// </summary>
        internal static string TitleAlert {
            get {
                return ResourceManager.GetString("TitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        internal static string TitleConfirmation {
            get {
                return ResourceManager.GetString("TitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка в базе данных.
        /// </summary>
        internal static string TitleErrorBD {
            get {
                return ResourceManager.GetString("TitleErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно!.
        /// </summary>
        internal static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль не соответствует требованиям безопасности! Требования: минимум 8 символов, наличие хотя бы одной цифры и заглавной латинской буквы..
        /// </summary>
        internal static string TooSimpleNewPassword {
            get {
                return ResourceManager.GetString("TooSimpleNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный пароль не соответствует требованиям безопасности! Требования: минимум 8 символов, наличие хотя бы одной цифры и заглавной латинской буквы..
        /// </summary>
        internal static string TooSimplePassword {
            get {
                return ResourceManager.GetString("TooSimplePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, попробуйте ещё раз!.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректная категория.
        /// </summary>
        internal static string UncorrectCategory {
            get {
                return ResourceManager.GetString("UncorrectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный ID клиента!.
        /// </summary>
        internal static string UncorrectIDClient {
            get {
                return ResourceManager.GetString("UncorrectIDClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректная цена.
        /// </summary>
        internal static string UncorrectPrice {
            get {
                return ResourceManager.GetString("UncorrectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        internal static string UnitDisplayMember {
            get {
                return ResourceManager.GetString("UnitDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица измерения не найдена!.
        /// </summary>
        internal static string UnitNotFound {
            get {
                return ResourceManager.GetString("UnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit_Id.
        /// </summary>
        internal static string UnitValueMember {
            get {
                return ResourceManager.GetString("UnitValueMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения данных в базу данных..
        /// </summary>
        internal static string UniversalErrorBD {
            get {
                return ResourceManager.GetString("UniversalErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введённый пароль не подтверждён. Пароли не совпадают..
        /// </summary>
        internal static string UnmatchedNewPasswords {
            get {
                return ResourceManager.GetString("UnmatchedNewPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные пароли не совпадают..
        /// </summary>
        internal static string UnmatchedPasswords {
            get {
                return ResourceManager.GetString("UnmatchedPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        internal static string UserRoleAdmin {
            get {
                return ResourceManager.GetString("UserRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin.
        /// </summary>
        internal static string UserRoleAdminEng {
            get {
                return ResourceManager.GetString("UserRoleAdminEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кладовщик.
        /// </summary>
        internal static string UserRoleWarehouseman {
            get {
                return ResourceManager.GetString("UserRoleWarehouseman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouseman.
        /// </summary>
        internal static string UserRoleWarehousemanEng {
            get {
                return ResourceManager.GetString("UserRoleWarehousemanEng", resourceCulture);
            }
        }
    }
}
