//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergeticProjectX.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergeticProjectX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка добавления товара в поставку.
        /// </summary>
        internal static string AddProductError {
            get {
                return ResourceManager.GetString("AddProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала добавьте товары для оформления отгрузки!.
        /// </summary>
        internal static string AddProductsInShipmentFirst {
            get {
                return ResourceManager.GetString("AddProductsInShipmentFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на успешно добавлен! Данные.
        /// </summary>
        internal static string AddProductSuccess {
            get {
                return ResourceManager.GetString("AddProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на уже добавлен в поставку.
        /// </summary>
        internal static string AlreadyInSupply {
            get {
                return ResourceManager.GetString("AlreadyInSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение продолжит работу..
        /// </summary>
        internal static string ApplicationWillContinue {
            get {
                return ResourceManager.GetString("ApplicationWillContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вам будут доступны следующие поля для редактирования: «Название товара», «Категория товара», «Цена закупки» и «Снижение цены»..
        /// </summary>
        internal static string AvailableFieldsToEditProduct {
            get {
                return ResourceManager.GetString("AvailableFieldsToEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно на складе:.
        /// </summary>
        internal static string AvailableInWarehouse {
            get {
                return ResourceManager.GetString("AvailableInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория успешно удалена!.
        /// </summary>
        internal static string CategorySuccessfullyDeleted {
            get {
                return ResourceManager.GetString("CategorySuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы изменили пароль!.
        /// </summary>
        internal static string ChangePasswordEvent {
            get {
                return ResourceManager.GetString("ChangePasswordEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию и/или новую единицу измерения для дальнейшего редактирования!.
        /// </summary>
        internal static string ChooseCategoryAndNewUnitToEdit {
            get {
                return ResourceManager.GetString("ChooseCategoryAndNewUnitToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала выберите категорию товара!.
        /// </summary>
        internal static string ChooseCategoryProductFirst {
            get {
                return ResourceManager.GetString("ChooseCategoryProductFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала выберите категорию для удаления!.
        /// </summary>
        internal static string ChooseCategoryToDeleteFirst {
            get {
                return ResourceManager.GetString("ChooseCategoryToDeleteFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала выберите клиента для редактирования!.
        /// </summary>
        internal static string ChooseClientToEditFirst {
            get {
                return ResourceManager.GetString("ChooseClientToEditFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала выберите клиента для совершения отгрузки!.
        /// </summary>
        internal static string ChooseClientToMakeShipmentFirst {
            get {
                return ResourceManager.GetString("ChooseClientToMakeShipmentFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, сначала выберите новую или текущую единицу измерения для редактирования категории..
        /// </summary>
        internal static string ChooseNewUnitToEditCategoryFirst {
            get {
                return ResourceManager.GetString("ChooseNewUnitToEditCategoryFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, сначала выберите товар!.
        /// </summary>
        internal static string ChooseProductFirst {
            get {
                return ResourceManager.GetString("ChooseProductFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала выберите товар для добавления в отгрузку!.
        /// </summary>
        internal static string ChooseProductToAddInShipmentFirst {
            get {
                return ResourceManager.GetString("ChooseProductToAddInShipmentFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка очистки скрытых категорий..
        /// </summary>
        internal static string CleanUpHiddenCategoriesError {
            get {
                return ResourceManager.GetString("CleanUpHiddenCategoriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка очистки скрытых клиентов..
        /// </summary>
        internal static string CleanUpHiddenClientsError {
            get {
                return ResourceManager.GetString("CleanUpHiddenClientsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка очистки скрытого товара..
        /// </summary>
        internal static string CleanUpHiddenProductsError {
            get {
                return ResourceManager.GetString("CleanUpHiddenProductsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получатель.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке клиентов..
        /// </summary>
        internal static string ClientsLoadError {
            get {
                return ResourceManager.GetString("ClientsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите отменить редактирование?.
        /// </summary>
        internal static string ConfirmationToCancelEdit {
            get {
                return ResourceManager.GetString("ConfirmationToCancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить данный товар?.
        /// </summary>
        internal static string ConfirmationToDeleteProduct {
            get {
                return ResourceManager.GetString("ConfirmationToDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось подключиться к базе данных. Пожалуйста, проверьте настройки подключения..
        /// </summary>
        internal static string ConnectionToDataBaseFailed {
            get {
                return ResourceManager.GetString("ConnectionToDataBaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Например: 05.05.2005.
        /// </summary>
        internal static string CorrectDateFormatExample {
            get {
                return ResourceManager.GetString("CorrectDateFormatExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформил.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата добавления.
        /// </summary>
        internal static string CreationData {
            get {
                return ResourceManager.GetString("CreationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка! Работа приостановлена..
        /// </summary>
        internal static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущая сессия была завершена или данные об аккаунте были утеряны. Пожалуйста, повторно пройдите авторизацию!.
        /// </summary>
        internal static string CurrentSessionWasInterruptedOrUserWasDeleted {
            get {
                return ResourceManager.GetString("CurrentSessionWasInterruptedOrUserWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата:.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снижение цены.
        /// </summary>
        internal static string DiscountDate {
            get {
                return ResourceManager.GetString("DiscountDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снижение цены должно быть произойти не раньше, чем через два месяца после создания..
        /// </summary>
        internal static string DiscountDateShouldNotBeEarlierThanCreationDate {
            get {
                return ResourceManager.GetString("DiscountDateShouldNotBeEarlierThanCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование категории.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечная дата не может быть позже текущего дня..
        /// </summary>
        internal static string EndDateCannotBeInFuture {
            get {
                return ResourceManager.GetString("EndDateCannotBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [EnsureCreatedError].
        /// </summary>
        internal static string EnsureCreatedError {
            get {
                return ResourceManager.GetString("EnsureCreatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки категорий..
        /// </summary>
        internal static string ErrorCategoryUpload {
            get {
                return ResourceManager.GetString("ErrorCategoryUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка назначения валюты по умолчанию..
        /// </summary>
        internal static string ErrorDefaultCurrencyUpload {
            get {
                return ResourceManager.GetString("ErrorDefaultCurrencyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при экспорте отчёта..
        /// </summary>
        internal static string ErrorExportReport {
            get {
                return ResourceManager.GetString("ErrorExportReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка удаления товара из отгрузки..
        /// </summary>
        internal static string ErrorProductDeleteFromShipment {
            get {
                return ResourceManager.GetString("ErrorProductDeleteFromShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения файла.
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении.
        /// </summary>
        internal static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения категории..
        /// </summary>
        internal static string ErrorSaveCategory {
            get {
                return ResourceManager.GetString("ErrorSaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки единиц измерения..
        /// </summary>
        internal static string ErrorUnitUpload {
            get {
                return ResourceManager.GetString("ErrorUnitUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки данных..
        /// </summary>
        internal static string ErrorUploadData {
            get {
                return ResourceManager.GetString("ErrorUploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки данных текущего пользователя..
        /// </summary>
        internal static string ErrorUserDataUpload {
            get {
                return ResourceManager.GetString("ErrorUserDataUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке данных!.
        /// </summary>
        internal static string ErrorWhileLoadingData {
            get {
                return ResourceManager.GetString("ErrorWhileLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс валюты:.
        /// </summary>
        internal static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курсы валют обновлены!.
        /// </summary>
        internal static string ExchangeRatesUploaded {
            get {
                return ResourceManager.GetString("ExchangeRatesUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переданный файл не содержит товаров.
        /// </summary>
        internal static string FileForSupplyNoProducts {
            get {
                return ResourceManager.GetString("FileForSupplyNoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиентов загружено:.
        /// </summary>
        internal static string HowMuchClientsUploaded {
            get {
                return ResourceManager.GetString("HowMuchClientsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлено валют:.
        /// </summary>
        internal static string HowMuchExchangeRatesUploaded {
            get {
                return ResourceManager.GetString("HowMuchExchangeRatesUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товара загружено:.
        /// </summary>
        internal static string HowMuchProductsUploaded {
            get {
                return ResourceManager.GetString("HowMuchProductsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователей загружено:.
        /// </summary>
        internal static string HowMuchUsersUploaded {
            get {
                return ResourceManager.GetString("HowMuchUsersUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратите внимание, что если закупочная цена данного товара изменится, также изменится и цена продажи!.
        /// </summary>
        internal static string IfChangePurchaseThenChangeSale {
            get {
                return ResourceManager.GetString("IfChangePurchaseThenChangeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат даты снижения цены, введите: dd.MM.yyyy..
        /// </summary>
        internal static string IncorrectDateFormat {
            get {
                return ResourceManager.GetString("IncorrectDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль..
        /// </summary>
        internal static string IncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("IncorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введён некорректный старый пароль..
        /// </summary>
        internal static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранная дата «До» не может быть раньше даты «С»..
        /// </summary>
        internal static string IncorrectPeriodOfDates {
            get {
                return ResourceManager.GetString("IncorrectPeriodOfDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный ИНН уже соответствует другому клиенту!.
        /// </summary>
        internal static string InnAlreadyExists {
            get {
                return ResourceManager.GetString("InnAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат данных для ИНН.
        /// </summary>
        internal static string INNFormatError {
            get {
                return ResourceManager.GetString("INNFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификационный номер юридического лица должен быть представлен комбинацией из 10 цифр.
        /// </summary>
        internal static string INNRequirementsTenDigits {
            get {
                return ResourceManager.GetString("INNRequirementsTenDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификационный номер физического лица лица или ИП должен быть представлен комбинацией из 12 цифр.
        /// </summary>
        internal static string INNRequirementsTwelveDigits {
            get {
                return ResourceManager.GetString("INNRequirementsTwelveDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректное количество товара для поставки.
        /// </summary>
        internal static string InputCorrectQuantity {
            get {
                return ResourceManager.GetString("InputCorrectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите новое название категории:.
        /// </summary>
        internal static string InputNewCategoryName {
            get {
                return ResourceManager.GetString("InputNewCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружено.
        /// </summary>
        internal static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышено допустимое число товара! Невозможно добавить товар..
        /// </summary>
        internal static string MaxNumberOfProducts {
            get {
                return ResourceManager.GetString("MaxNumberOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая категория, которую Вы хотите добавить, уже существует!.
        /// </summary>
        internal static string NewCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("NewCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название категории не может быть пустым..
        /// </summary>
        internal static string NewCategoryNameShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("NewCategoryNameShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая категория успешно добавлена!.
        /// </summary>
        internal static string NewCategorySuccessfullyAdded {
            get {
                return ResourceManager.GetString("NewCategorySuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущая валюта:.
        /// </summary>
        internal static string NewCurrency {
            get {
                return ResourceManager.GetString("NewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ни один товар не был загружен.
        /// </summary>
        internal static string NoProductsLoaded {
            get {
                return ResourceManager.GetString("NoProductsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала добавьте товары в поставку!.
        /// </summary>
        internal static string NoProductsToAdd {
            get {
                return ResourceManager.GetString("NoProductsToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось обновить курсы валют!.
        /// </summary>
        internal static string NotManagedToUploadExchangeRates {
            get {
                return ResourceManager.GetString("NotManagedToUploadExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестно.
        /// </summary>
        internal static string Notstated {
            get {
                return ResourceManager.GetString("Notstated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить пароль на уже существующий. Пожалуйста, придумайте новый пароль для замены!.
        /// </summary>
        internal static string OldAndNewPasswordsTheSame {
            get {
                return ResourceManager.GetString("OldAndNewPasswordsTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личные данные должны содержать только буквы..
        /// </summary>
        internal static string PersonalDataIsIrrelevant {
            get {
                return ResourceManager.GetString("PersonalDataIsIrrelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, подождите!.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при добавлении товара в отгрузку.
        /// </summary>
        internal static string ProductAddToShipmentError {
            get {
                return ResourceManager.GetString("ProductAddToShipmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар не найден..
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на товаров из файла.
        /// </summary>
        internal static string ProductsFromFile {
            get {
                return ResourceManager.GetString("ProductsFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество товара:.
        /// </summary>
        internal static string ProductsNumber {
            get {
                return ResourceManager.GetString("ProductsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество товара:.
        /// </summary>
        internal static string ProductsQuantity {
            get {
                return ResourceManager.GetString("ProductsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно удален!.
        /// </summary>
        internal static string ProductSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("ProductSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выручка.
        /// </summary>
        internal static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закупочная цена.
        /// </summary>
        internal static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закупочная цена должна быть числом!.
        /// </summary>
        internal static string PurchasePriceIsSupposedToBeNumber {
            get {
                return ResourceManager.GetString("PurchasePriceIsSupposedToBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введено слишком большое число!.
        /// </summary>
        internal static string PurchasePriceOverflowException {
            get {
                return ResourceManager.GetString("PurchasePriceOverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закупочная цена должна быть положительным числом!.
        /// </summary>
        internal static string PurchasePriceShouldNotBeNegative {
            get {
                return ResourceManager.GetString("PurchasePriceShouldNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчёт успешно экспортирован!.
        /// </summary>
        internal static string ReportSuccessfullyExported {
            get {
                return ResourceManager.GetString("ReportSuccessfullyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выручка.
        /// </summary>
        internal static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена продажи.
        /// </summary>
        internal static string SalePrice {
            get {
                return ResourceManager.GetString("SalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При сохранении изменений данная категория изменится у всех товаров этой категории!.
        /// </summary>
        internal static string SaveCategoryChangeConsequences {
            get {
                return ResourceManager.GetString("SaveCategoryChangeConsequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить отчёт как:.
        /// </summary>
        internal static string SaveReportAs {
            get {
                return ResourceManager.GetString("SaveReportAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении отгрузки..
        /// </summary>
        internal static string SaveShipmentError {
            get {
                return ResourceManager.GetString("SaveShipmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите валюту!.
        /// </summary>
        internal static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала выберите товар для удаления!.
        /// </summary>
        internal static string SelectProductToDeleteFirst {
            get {
                return ResourceManager.GetString("SelectProductToDeleteFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите отгрузку для просмотра подробностей!.
        /// </summary>
        internal static string SelectShipmentForDetails {
            get {
                return ResourceManager.GetString("SelectShipmentForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки успешно сохранены!.
        /// </summary>
        internal static string SettingsSuccessfullySaved {
            get {
                return ResourceManager.GetString("SettingsSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка успешно оформлена..
        /// </summary>
        internal static string ShipmentSuccessfullyProcessed {
            get {
                return ResourceManager.GetString("ShipmentSuccessfullyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальная дата не может быть позже текущего дня..
        /// </summary>
        internal static string StartDateCannotBeInFuture {
            get {
                return ResourceManager.GetString("StartDateCannotBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий остаток: 0 (по умолчанию).
        /// </summary>
        internal static string StockQuantityByDefault {
            get {
                return ResourceManager.GetString("StockQuantityByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара на складе..
        /// </summary>
        internal static string StockQuantityIsNotEnough {
            get {
                return ResourceManager.GetString("StockQuantityIsNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория успешно обновлена!.
        /// </summary>
        internal static string SuccessUpdateCategory {
            get {
                return ResourceManager.GetString("SuccessUpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно обновлён!.
        /// </summary>
        internal static string SuccessUpdateProduct {
            get {
                return ResourceManager.GetString("SuccessUpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставка успешно оформлена!.
        /// </summary>
        internal static string SupplySuccessfullyProcessed {
            get {
                return ResourceManager.GetString("SupplySuccessfullyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма поставки:.
        /// </summary>
        internal static string SupplySum {
            get {
                return ResourceManager.GetString("SupplySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите редактировать карточку данного товара?.
        /// </summary>
        internal static string SureWantToChangeProductData {
            get {
                return ResourceManager.GetString("SureWantToChangeProductData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить категорию:.
        /// </summary>
        internal static string SureWantToDeleteCategory {
            get {
                return ResourceManager.GetString("SureWantToDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить клиента:.
        /// </summary>
        internal static string SureWantToDeleteClient {
            get {
                return ResourceManager.GetString("SureWantToDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите оформить отгрузку?.
        /// </summary>
        internal static string SureWantToMakeShipment {
            get {
                return ResourceManager.GetString("SureWantToMakeShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформить действительно хотите оформить поставку?.
        /// </summary>
        internal static string SureWantToMakeSupply {
            get {
                return ResourceManager.GetString("SureWantToMakeSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите сохранить данные изменения?.
        /// </summary>
        internal static string SureWantToSaveCategoryChange {
            get {
                return ResourceManager.GetString("SureWantToSaveCategoryChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет информации для экспорта. Необходимо выбрать другую дату..
        /// </summary>
        internal static string ThereIsNoDataToExport {
            get {
                return ResourceManager.GetString("ThereIsNoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление.
        /// </summary>
        internal static string TitleAlert {
            get {
                return ResourceManager.GetString("TitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        internal static string TitleConfirmation {
            get {
                return ResourceManager.GetString("TitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль не соответствует требованиям безопасности! Требования: минимум 8 символов, наличие хотя бы одной цифры и заглавной латинской буквы..
        /// </summary>
        internal static string TooSimpleNewPassword {
            get {
                return ResourceManager.GetString("TooSimpleNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный пароль не соответствует требованиям безопасности! Требования: минимум 8 символов, наличие хотя бы одной цифры и заглавной латинской буквы..
        /// </summary>
        internal static string TooSimplePassword {
            get {
                return ResourceManager.GetString("TooSimplePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибыль:.
        /// </summary>
        internal static string TotalProfit {
            get {
                return ResourceManager.GetString("TotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выручка:.
        /// </summary>
        internal static string TotalRevenue {
            get {
                return ResourceManager.GetString("TotalRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число отгрузок:.
        /// </summary>
        internal static string TotalShipments {
            get {
                return ResourceManager.GetString("TotalShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, попробуйте ещё раз!.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка указать:.
        /// </summary>
        internal static string TryToPoint {
            get {
                return ResourceManager.GetString("TryToPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица измерения для соответствующей категории не найдена..
        /// </summary>
        internal static string UnitForChosenCategoryNotFound {
            get {
                return ResourceManager.GetString("UnitForChosenCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения данных в базу данных..
        /// </summary>
        internal static string UniversalErrorDatabase {
            get {
                return ResourceManager.GetString("UniversalErrorDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введённый пароль не подтверждён. Пароли не совпадают..
        /// </summary>
        internal static string UnmatchedNewPasswords {
            get {
                return ResourceManager.GetString("UnmatchedNewPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные пароли не совпадают..
        /// </summary>
        internal static string UnmatchedPasswords {
            get {
                return ResourceManager.GetString("UnmatchedPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все несохранённые изменения будут утеряны!.
        /// </summary>
        internal static string UnsavedChangesWillBeLost {
            get {
                return ResourceManager.GetString("UnsavedChangesWillBeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление курсов валют....
        /// </summary>
        internal static string UploadingExchangeRates {
            get {
                return ResourceManager.GetString("UploadingExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта пользователя не найдена..
        /// </summary>
        internal static string UserCurrencyNotFound {
            get {
                return ResourceManager.GetString("UserCurrencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином уже существует! Пожалуйста, придумайте новый логин..
        /// </summary>
        internal static string UserLoginAlreadyExists {
            get {
                return ResourceManager.GetString("UserLoginAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается закупочная цена товара. Пожалуйста, введите закупочную цену..
        /// </summary>
        internal static string WaitingToEnterThePrice {
            get {
                return ResourceManager.GetString("WaitingToEnterThePrice", resourceCulture);
            }
        }
    }
}
